#!/usr/bin/env python3
import json, os, re, socket, subprocess, time, urllib.request, zipfile
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

PORT = 8099
CONFIG = Path('/config')
SHARE = Path('/share')
SUPERVISOR = 'http://supervisor'
SENSITIVE = re.compile(r'(token|password|secret|username|access_token|refresh_token|authorization|cookie|email)', re.I)


def now():
    return datetime.now(timezone.utc).isoformat()


def safe_value(k, v):
    if SENSITIVE.search(str(k)):
        return '***REDACTED***'
    if isinstance(v, dict):
        return {str(x): safe_value(x, y) for x, y in v.items()}
    if isinstance(v, list):
        return [safe_value('', x) for x in v]
    return v


def read_text(path, limit=250000):
    try:
        return path.read_text(errors='replace')[:limit]
    except Exception as e:
        return f'[read error: {e}]'


def find_files(root, patterns, max_files=300):
    out=[]
    if not root.exists(): return out
    try:
        for p in root.rglob('*'):
            if len(out) >= max_files: break
            if p.is_file() and any(p.match(x) for x in patterns): out.append(p)
    except Exception:
        pass
    return out


def source_inventory():
    roots=[]
    for name in ('custom_components', 'www'):
        p=CONFIG/name
        if p.exists(): roots.append(p)
    matches=[]
    for root in roots:
        try:
            for p in root.rglob('*'):
                if p.is_file() and p.suffix in ('.py','.yaml','.yml','.json','.txt'):
                    text=read_text(p, 120000)
                    if 'deebot' in text.lower() or 'ecovacs' in text.lower():
                        matches.append({'path':str(p),'size':p.stat().st_size,'hits':len(re.findall('deebot|ecovacs', text, re.I))})
        except Exception:
            pass
    return matches[:500]


def extract_methods():
    methods=['OnMajorMap','OnMapInfoV2','OnCachedMapInfo','GetMajorMap','GetMapTrace','GetMapInfoV2','GetCachedMapInfo','GetDeviceInfo']
    found={m:[] for m in methods}
    for item in source_inventory():
        text=read_text(Path(item['path']), 250000)
        for m in methods:
            if re.search(r'\b'+re.escape(m)+r'\b', text): found[m].append(item['path'])
    return found


def ha_api(path):
    token=os.environ.get('SUPERVISOR_TOKEN')
    if not token: return {'error':'SUPERVISOR_TOKEN unavailable'}
    req=urllib.request.Request(SUPERVISOR+path, headers={'Authorization':'Bearer '+token})
    try:
        with urllib.request.urlopen(req, timeout=8) as r:
            return json.loads(r.read().decode())
    except Exception as e:
        return {'error':str(e)}


def config_entries():
    p=CONFIG/'.storage/core.config_entries'
    if not p.exists(): return {'error':'core.config_entries not found'}
    try:
        data=json.loads(read_text(p, 2000000))
        entries=data.get('data',{}).get('entries',[])
        deebot=[]
        for e in entries:
            if 'deebot' in str(e.get('domain','')).lower() or 'ecovacs' in str(e).lower():
                deebot.append(safe_value('', e))
        return {'count':len(deebot),'entries':deebot}
    except Exception as e: return {'error':str(e)}


def diagnostic():
    states=ha_api('/core/api/states')
    vacuum_states=[]
    if isinstance(states,list):
        for s in states:
            eid=s.get('entity_id','')
            if 'vacuum' in eid.lower() or 'deebot' in eid.lower() or 'ecovacs' in eid.lower():
                vacuum_states.append(safe_value('',s))
    info=ha_api('/supervisor/info')
    return {
        'generated_at':now(),
        'hostname':socket.gethostname(),
        'add_on':{'version':'0.1.0'},
        'environment':{'python':subprocess.run(['python3','--version'],capture_output=True,text=True).stdout.strip(),'arch':os.uname().machine},
        'home_assistant':safe_value('',info),
        'deebot_entities':vacuum_states,
        'config_entries':config_entries(),
        'source_inventory':source_inventory(),
        'methods':extract_methods(),
        'known_y1_pro_methods':['OnMajorMap','OnMapInfoV2','OnCachedMapInfo','GetMajorMap','GetMapTrace','GetMapInfoV2','GetCachedMapInfo','GetDeviceInfo'],
    }


def make_bundle():
    data=diagnostic()
    stamp=datetime.now().strftime('%Y%m%d-%H%M%S')
    out=SHARE/f'deebot-y1pro-diagnostic-{stamp}.zip'
    with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
        z.writestr('diagnostic.json',json.dumps(data,indent=2,default=str))
        z.writestr('methods.json',json.dumps(data['methods'],indent=2))
        z.writestr('source-inventory.json',json.dumps(data['source_inventory'],indent=2))
        z.writestr('README.txt','Generated by DEEBOT Y1 PRO Diagnostic Toolkit. Secrets are redacted where detected.\n')
    return str(out)

HTML='''<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>DEEBOT Diagnostics</title><style>body{font-family:system-ui;max-width:1100px;margin:30px auto;padding:0 18px}button{padding:10px 14px;margin:4px}pre{white-space:pre-wrap;background:#f4f4f4;padding:14px;border-radius:8px}h2{margin-top:28px}.ok{color:#087f23}.bad{color:#b00020}</style></head><body><h1>DEEBOT Y1 PRO Diagnostics</h1><p>Read-only diagnostic toolkit for Home Assistant.</p><button onclick="run()">Run full diagnostic</button><button onclick="bundle()">Create diagnostic bundle</button><div id="out"><p>Ready.</p></div><script>async function run(){out.innerHTML='<p>Running...</p>';let r=await fetch('api/diagnostic');let d=await r.json();out.innerHTML='<h2>Summary</h2><pre>'+JSON.stringify(d,null,2)+'</pre>'}async function bundle(){let r=await fetch('api/bundle',{method:'POST'});let d=await r.json();out.innerHTML='<h2>Bundle</h2><pre>'+JSON.stringify(d,null,2)+'</pre>'}</script></body></html>'''

class Handler(BaseHTTPRequestHandler):
    def send(self, code, body, ctype='application/json'):
        b=body.encode() if isinstance(body,str) else body
        self.send_response(code); self.send_header('Content-Type',ctype); self.send_header('Content-Length',str(len(b))); self.end_headers(); self.wfile.write(b)
    def do_GET(self):
        if self.path in ('/',''):
            return self.send(200,HTML,'text/html; charset=utf-8')
        if self.path.startswith('/api/diagnostic'):
            return self.send(200,json.dumps(diagnostic(),indent=2,default=str))
        self.send(404,json.dumps({'error':'not found'}))
    def do_POST(self):
        if self.path.startswith('/api/bundle'):
            try: return self.send(200,json.dumps({'bundle':make_bundle()}))
            except Exception as e: return self.send(500,json.dumps({'error':str(e)}))
        self.send(404,json.dumps({'error':'not found'}))
    def log_message(self, *_): pass

if __name__=='__main__':
    HTTPServer(('0.0.0.0',PORT),Handler).serve_forever()
